version: '3.8'
services:
  waarzitjenu-map:
    environment:
      - MAPBOX_ACCESS_TOKEN
      - LOCATION_API_ENDPOINT
    build:
      context: 'https://github.com/waarzitjenu/map.git'
      dockerfile: Dockerfile
    ports:
      - 80:80

  waarzitjenu-server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - waarzitjenu-server-db:/go/src/waarzitjenu/server/database/

volumes:
  waarzitjenu-server-db: {} # The database files, needs to stay persistent and can also be attached to other services.
